const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script); // Parse the entire embedded script, not just the exercised functions.
function extract(start, end) { return script.slice(script.indexOf(start), script.indexOf(end, script.indexOf(start))); }
const elements = {};
const el = id => elements[id] ||= { value: '', style: {}, textContent: '', innerHTML: '' };
const ctx = vm.createContext({ $: el, esc: s => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;'), relTime: () => '刚刚', mdLite: s => s, Date, TextEncoder, window: { addEventListener() {} }, document: { addEventListener() {} } });
vm.runInContext('let S; let updInfo;\n' + extract('function compareMemberActivity', 'function switchTab') + extract('function fmtCheckedAt', 'async function onUpdateClick'), ctx);
vm.runInContext(`S = {members: [{peer_id:'peer1', virtual_ip:'10.7.1.2', virtual_ipv6:'fd00:6c61:6e65::1234', online:true}]}; renderMembers();`, ctx);
assert.match(el('members').innerHTML, /10\.7\.1\.2/);
let copiedIPv4;
ctx.copyText = text => { copiedIPv4 = text; };
const ipv4Click = el('members').innerHTML.match(/onclick="(copyText\('10\.7\.1\.2', this\))"/);
assert.ok(ipv4Click, 'IPv4 must have a copy handler');
vm.runInContext(ipv4Click[1], ctx);
assert.equal(copiedIPv4, '10.7.1.2');
assert.match(el('members').innerHTML, /fd00:6c61:6e65::1234/);
assert.match(el('members').innerHTML, /class="m-ipv6"/);
el('mSearch').value = 'FD00:6C61';
assert.equal(vm.runInContext('filteredMembers().length', ctx), 1);
el('mSearch').value = '';
vm.runInContext('delete S.members[0].virtual_ipv6; renderMembers();', ctx);
assert.doesNotMatch(el('members').innerHTML, /undefined|class="m-ipv6"/);
vm.runInContext('delete S.members[0].virtual_ip; renderMembers();', ctx);
assert.doesNotMatch(el('members').innerHTML, /onclick="copyText/);
vm.runInContext(extract('function seedSpecCheck', '// bootstrapPasteHint') + extract('function copySeedMine', '// ---- 连接种子') + extract('function renderSeed', 'let cfg'), ctx);
const seeds = ['/ip4/43.136.124.167/tcp/4001/p2p/12D3KooWD1RmFbKp7sEmmeRepvQnfpZcLRxQXXGabin21k5zm8Kf', '/ip4/43.136.124.167/udp/4001/quic-v1/p2p/12D3KooWD1RmFbKp7sEmmeRepvQnfpZcLRxQXXGabin21k5zm8Kf'];
ctx.autoGrow = () => {}; ctx.flash = () => {}; let copied;
ctx.copyText = text => { copied = text; };
ctx.seeds = seeds;
vm.runInContext('S.seed_addrs = seeds; renderSeed(); copySeedMine();', ctx);
assert.equal(copied, el('seedMine').value);
assert.match(html, /<textarea id="cBootstrap"/);
for (const separator of ['\n', '\r\n', ' ', '\t', ',']) {
  el('cBootstrap').value = seeds.join(separator);
  assert.equal(vm.runInContext("seedSpecCheck($('cBootstrap').value)", ctx), '');
  const submission = script.match(/bootstrap: ([^\n]+),/)[1];
  assert.equal(vm.runInContext(submission, ctx), seeds.join(','));
}
vm.runInContext(`S.members = [{peer_id:'never',virtual_ip:'10.7.0.1',online:false},{peer_id:'old',virtual_ip:'10.7.0.2',online:false,last_seen:100},{peer_id:'recent',virtual_ip:'10.7.0.3',online:false,last_seen:200},{peer_id:'online',virtual_ip:'10.7.0.4',online:true}];`, ctx);
assert.equal(vm.runInContext('filteredMembers().map(m => m.peer_id).join(",")', ctx), 'online,recent,old,never');
vm.runInContext('renderMembers()', ctx);
assert.match(el('members').innerHTML, /无已验证活跃记录/);
const output = el('logOutput');
output.scrollTop = 137;
output.children = [];
output.replaceChildren = () => { output.children = []; };
output.appendChild = fragment => { output.children.push(...fragment.children); };
ctx.document.createDocumentFragment = () => ({ children: [], appendChild(node) { this.children.push(node); } });
ctx.document.createElement = () => ({ textContent: '', remove() { output.children.splice(output.children.indexOf(this), 1); } });
ctx.batch = { reset: false, cursor: 1, generation: 1, more: true, records: Array.from({length: 2100}, () => ({text: '<script>test</script>'})) };
vm.runInContext('appendLogBatch(batch)', ctx);
assert.equal(output.children.length, 2048, 'log DOM must stay bounded');
assert.equal(output.scrollTop, 137, 'log batches must not auto-scroll');
assert.equal(output.children[0].textContent, '<script>test</script>', 'logs must render as text');
ctx.batch = { reset: true, cursor: 2, generation: 2, more: false, records: [{text: 'after clear'}] };
vm.runInContext('appendLogBatch(batch)', ctx);
assert.equal(output.children.length, 1, 'generation reset must discard old history');
assert.equal(output.children[0].textContent, 'after clear');
console.log('PASS: script syntax, IPv6 rendering/search, seed display-copy-paste-submit, bounded safe logs without auto-scroll');
